Detect builder repo and ref from oidc token (#25)
* detect builder repo and ref from oidc token

Signed-off-by: Asra Ali <asraa@google.com>

diff --git a/.github/workflows/builder.yml b/.github/workflows/builder.yml
--- a/.github/workflows/builder.yml
+++ b/.github/workflows/builder.yml
@@ -23,9 +23,6 @@ env:
   GENERATED_BINARY_NAME: compiled-binary
   # Builder
   BUILDER_BINARY: builder
-  # This repo.
-  BUILDER_REPOSITORY: slsa-framework/slsa-github-generator-go
-  BUILDER_REF: main
 
 ###################################################################
 #                                                                 #
@@ -54,18 +51,46 @@ jobs:
   #                       Build the builder                         #
   #                                                                 #
   ###################################################################
+  detect-env:
+    runs-on: ubuntu-latest
+    permissions:
+      id-token: write # Needed to detect the current reusable repository and ref.
+      contents: read
+    outputs:
+      builder_repo: ${{ steps.detect.outputs.builder_repo }}
+      builder_ref: ${{ steps.detect.outputs.builder_ref }}
+    steps:
+      - name: Detect the builder ref
+        id: detect
+        shell: bash
+        run: | 
+          status_code=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=slsa-framework/slsa-github-generator-go/builder" -o jwt.json -w '%{http_code}')
+          if [[ $status_code -ge 400 ]]; then
+              error_msg=$(jq -r .message jwt.json 2>/dev/null || echo 'unknown error')
+              echo "Failed to get OIDC token from GitHub, response $status_code: $error_msg"
+              exit 1;
+          fi
+          export WORKFLOW_REF=$(cat jwt.json | jq -r '.value' | cut -d "." -f2 | base64 -d | jq -r '.job_workflow_ref')
+          if [ -z $WORKFLOW_REF ]; then
+            echo "OIDC token parsing failure: job_workflow_ref could not be retrieved"
+            exit 1;
+          fi
+          echo "::set-output name=builder_repo::$(echo $WORKFLOW_REF | cut -d "@" -f1 | cut -d '/' -f1-2)"
+          echo "::set-output name=builder_ref::$(echo $WORKFLOW_REF | cut -d "@" -f2)"
+
   builder:
     outputs:
       go-builder-sha256: ${{ steps.builder-gen.outputs.go-builder-sha256 }}
       go-prov-sha256: ${{ steps.builder-gen.outputs.go-prov-sha256 }}
     runs-on: ubuntu-latest
+    needs: [detect-env]
     steps:
       - name: Checkout the repository
         uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.3.4
         with:
           fetch-depth: 0
-          repository: "${{ env.BUILDER_REPOSITORY }}"
-          ref: "${{ env.BUILDER_REF }}"
+          repository: "${{ needs.detect-env.outputs.builder_repo }}"
+          ref: "${{ needs.detect-env.outputs.builder_ref }}"
 
       - name: Set up golang environment
         uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.1.3
